"""empty message

Revision ID: 08ac17d091d4
Revises: 6862e8af6ab5
Create Date: 2018-08-07 15:19:45.571000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ac17d091d4'
down_revision = '6862e8af6ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('productId', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('productId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###
