"""empty message

Revision ID: 8bb30c62f16b
Revises: 08ac17d091d4
Create Date: 2018-08-07 15:22:23.857000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb30c62f16b'
down_revision = '08ac17d091d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('MRP', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('batchDate', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('batchNum', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('productName', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('quantity', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('inventory', sa.Column('vendor', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'vendor')
    op.drop_column('inventory', 'status')
    op.drop_column('inventory', 'quantity')
    op.drop_column('inventory', 'productName')
    op.drop_column('inventory', 'batchNum')
    op.drop_column('inventory', 'batchDate')
    op.drop_column('inventory', 'MRP')
    # ### end Alembic commands ###
